### ISSUE TITLE
Getting type_argument from function annotation

### ISSUE THREAD

**Issue by notpushkin** [dry-python/classes#136]
Hey @sobolevn!

[`functools.singledispatch`][sd] now supports using type annotations instead of passing an argument: 

```py
@singledispatch
def fun(arg, verbose=False):
    ...

@fun.register
def _(arg: int, verbose=False):
    ...
```

The old syntax still works, but in simple cases like here this helps reduce unnecessary repetition and, as a result, the code looks a bit cleaner.

Would you be interesting in accepting a PR implementing similar interface for `_TypeClass.instance`?

[sd]: https://docs.python.org/3/library/functools.html#functools.singledispatch

**Comment by sobolevn** [comment]
I would love to!
