### ISSUE TITLE
Support `Type[]` type with `delegate`

### ISSUE THREAD

**Issue by sobolevn** [dry-python/classes#275]
Currently, we cannot express something like:

```python
@some.instance(Type[MyClass], delegate=MyDelegate)
def _some_type_myclass(instance: Type[MyClass]) -> int: ...
```

We can only dispatch on `type` and that's it.
I think that this feature is useful.

Related #264 
Related #274

**Comment by thepabloaguilar** [comment]
In fact we cannot express the example below without delegate too since `Type` is a generic thing:
```python
@some.instance(Type[MyClass])
def _some_type_myclass(instance: Type[MyClass]) -> int: ...
```

What's the goal of this issue, enable `Type` in `.instance` or enable `Type` just for delegated typeclasses?

**Comment by sobolevn** [comment]
Yes, you are right! It should be:

```python
@some.instance(delegate=MyTypeDelegate)
def _some_type_myclass(instance: Type[MyClass]) -> int: ...
```

**Comment by thepabloaguilar** [comment]
So, what we need to do here? Like, the delegated classes are something that the users pass and that have the highest priority when we're evaluating the values

**Comment by sobolevn** [comment]
We need to make sure that the example above works and type-checks 🙂

**Comment by thepabloaguilar** [comment]
I'd like to propose that we provide some delegate classes. Like this one that will check a Type because in order to do that check the users must know how to use `get_origin` and `get_args` from typing that's tricky sometimes!

> P.S.: I made `@example.instance(Type[MyClass]) works and all unit tests passed! Maybe we can add `.type` decorator

**Comment by sobolevn** [comment]
@thepabloaguilar great idea! Please, create a new issue for that! 👍
