### ISSUE TITLE
Bug with mypy plugin

### ISSUE THREAD

**Issue by thomasborgen** [dry-python/classes#344]
# Bug report

## What's wrong

mypy plugin is not working

`setup.cfg:2: error: Error importing plugin "classes.contrib.mypy.classes_plugin": cannot import name 'TypeVarDef' from 'mypy.types' (/home/thomas/opensource/classes-mypy-problem/.venv/lib/python3.9/site-packages/mypy/types.cpython-39-x86_64-linux-gnu.so)`

## How is that should be

`poetry run mypy .` should work ^^

heres a repo that reproduces the issue:

[repo](https://github.com/thomasborgen/dry-python-classes-mypy-issue)

## System information

- `python` version: 3.9.7
- `classes` version: 0.4.0
- `mypy` version: 0.921

**Comment by sobolevn** [comment]
`classes` is not yet compatible with `mypy>=0.920`

**Comment by thomasborgen** [comment]
Sry, my bad, I just saw that this was merged https://github.com/dry-python/classes/pull/343
And didn't think it through that that was just dev dependencies for classes ^^.
