### ISSUE TITLE
Syntax error in mermaid scheme on concept page

### ISSUE THREAD

**Issue by ivanovmg** [dry-python/classes#489]
# Bug report

## What's wrong

When I go to https://classes.readthedocs.io/en/latest/pages/concept.html I can see that the scheme, which follows the sentence "To use typeclasses you should understand these steps:" is not shown properly.

![image](https://github.com/user-attachments/assets/1dbb1bf3-2b70-4308-a7e3-7e9ee54ffea9)

## How is that should be

It should show the scheme without "Syntax error" highlight.

Syntax error in https://github.com/dry-python/classes/blob/master/docs/pages/concept.rst#steps should probably be fixed.

**Comment by sobolevn** [comment]
PR is welcome!

**Comment by ivanovmg** [comment]
I revisited the issue once again.
Now I can see that the syntax error is not visible anymore.
Checked in Microsoft Edge and Firefox.

It is likely that the issue was related to the particular version of mermaid.js script.
As of now, the script has version [11.4.1](https://unpkg.com/mermaid@11.4.1/dist/mermaid.min.js) and it works fine.

Thus, I am closing the issue.
