### ISSUE TITLE
Multiple dispatcher

### ISSUE THREAD

**Issue by AndreyErmilov** [dry-python/classes#66]
Hi @sobolevn 

It would be great to do something with an interface like this
``` python
@impl
def add(a: int, b: int) -> int:
    return a + b

@impl
def add(a: str, b: str) -> str:
    return '{0}{1}'.format(a, b)
```

If it's not a good idea to parse in runtime type annotations
``` python
@impl(int, int)
def add(a: int, int) -> int:
    return a + b

@impl(str, str)
def add(a: str, b: str) -> str:
    return '{0}{1}'.format(a, b)
```
What do you think?

**Comment by sobolevn** [comment]
It looks like a very hard thing to implement. The main problem is that `Python` does not have a lot of types at runtime.

For example, `@impl(List[int], Callable[[int], int]` will never be called. There are no `List` and especially `List[int]`.
And `Callable[[int], int]` is a protocol:
```
>>> isinstance(int, Callable[[int], int])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sobolev/.pyenv/versions/3.7.7/lib/python3.7/typing.py", line 713, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/Users/sobolev/.pyenv/versions/3.7.7/lib/python3.7/typing.py", line 721, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

So, we will have to:
1. Infer types at runtime
2. Dispatch them correctly

This is way too hard.

**Comment by AndreyErmilov** [comment]
Okay, thanks!
